kibana.defaultAppId: "discover"
logging.dest: /var/log/kolla/kibana/kibana.log
server.port: 5601
server.host: "192.168.178.54"
elasticsearch.url: "http://192.168.178.254:9200"
elasticsearch.requestTimeout: 300000
elasticsearch.shardTimeout: 0
elasticsearch.ssl.verificationMode: "none"

# Custom
xpack.security.authc.token.enabled: true
